// <auto-generated />
using ElectronicStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectronicStore.Models.ProductModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ElectronicStore.Models.AirConditioner", b =>
                {
                    b.HasBaseType("ElectronicStore.Models.ProductModel");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AirConditioners", (string)null);
                });

            modelBuilder.Entity("ElectronicStore.Models.Television", b =>
                {
                    b.HasBaseType("ElectronicStore.Models.ProductModel");

                    b.Property<int>("ScreenSize")
                        .HasColumnType("int");

                    b.ToTable("Televisions", (string)null);
                });

            modelBuilder.Entity("ElectronicStore.Models.WashingMachine", b =>
                {
                    b.HasBaseType("ElectronicStore.Models.ProductModel");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.ToTable("WashingMachines", (string)null);
                });

            modelBuilder.Entity("ElectronicStore.Models.AirConditioner", b =>
                {
                    b.HasOne("ElectronicStore.Models.ProductModel", null)
                        .WithOne()
                        .HasForeignKey("ElectronicStore.Models.AirConditioner", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicStore.Models.Television", b =>
                {
                    b.HasOne("ElectronicStore.Models.ProductModel", null)
                        .WithOne()
                        .HasForeignKey("ElectronicStore.Models.Television", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicStore.Models.WashingMachine", b =>
                {
                    b.HasOne("ElectronicStore.Models.ProductModel", null)
                        .WithOne()
                        .HasForeignKey("ElectronicStore.Models.WashingMachine", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
